root = "."
tmp_dir = "tmp"
testdata_dir = "testdata"

[build]
  cmd = "go build -o ./tmp/main ./cmd/api/main.go"
  full_bin = "./tmp/main"
  delay = 1000

  # Include only things Air must watch
  include_ext = ["go", "tpl", "tmpl", "html"]

  # Exclude irrelevant directories
  exclude_dir = [
    "assets",
    "tmp",
    "vendor",
    "testdata",
    "node_modules",
    "dist"
  ]

  exclude_regex = ["_test\\.go"]
  log = "build-errors.log"
  stop_on_error = false
  kill_delay = "0s"
  rerun_delay = 500
  clear_on_rebuild = true

[color]
  main = "magenta"
  runner = "green"
  watcher = "cyan"
  build = "yellow"

[log]
  time = false
  main_only = false

[misc]
  clean_on_exit = false

[screen]
  clear_on_rebuild = true
  keep_scroll = true
